# 1. Aapki ID Details
sonar.organization=ssiddiquiii
sonar.projectKey=ssiddiquiii_note-app

# 2. Universal Scan (Dot (.) ka matlab "Sab kuch scan karo")
sonar.sources=.

# 3. Kachra Hatao (In files ko ignore karna hai)
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.jsx,**/*.test.js,**/__tests__/**,**/*.config.js

# 4. Encoding
sonar.sourceEncoding=UTF-8