# 1. Project Identification
sonar.organization=ssiddiquiii
sonar.projectKey=ssiddiquiii_note-app

# 2. Source Code Path (Dot = Sab kuch scan karo)
sonar.sources=.

# 3. Exclusions (In files ko ignore karo)
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.jsx,**/*.test.js,**/__tests__/**

# 4. Encoding
sonar.sourceEncoding=UTF-8